### ISSUE TITLE
Rule: unused private members

### ISSUE THREAD

**Issue by tvsonar** [SonarSource-VisualStudio/sonarlint-roslyn-analyzer#166]
R# id: _UnusedProperty_, _UnusedMember.Local_

Private members (method, property, field, nested type, indexer, event) that are never used can be safely removed.

**Comment by ganncamp** [comment]
I've mapped the id's to these 2 existing rules:
http://jira.sonarsource.com/browse/RSPEC-1144
http://jira.sonarsource.com/browse/RSPEC-1068
