### ISSUE TITLE
Rule: Object or collection initializer should be used when possible

### ISSUE THREAD

**Issue by tvsonar** [SonarSource-VisualStudio/sonarlint-roslyn-analyzer#170]
R# rule ID: _UseObjectOrCollectionInitializer_

If a constructor call is followed by property setters, or a collection creation is followed by `Add` method calls, then these subsequent calls can be merged into the construction of the object:
```
var p = new Person();
p.Age = 5;
p.Name = "John";
```
can be converted to 
```
var p = new Person 
  {
    Age = 5,
    Name = "John"
  };
```

Similarly
```
var l = new List<int>();
l.Add(5);
l.Add(10);
```
is equivalent to
```
var l = new List<int> {5, 10};
```

**Comment by ganncamp** [comment]
http://jira.sonarsource.com/browse/RSPEC-3325
