### ISSUE TITLE
Rule: a try-catch block nested inside a try-finally block can be merged

### ISSUE THREAD

**Issue by tvsonar** [SonarSource-VisualStudio/sonarlint-roslyn-analyzer#172]
RSPEC: http://jira.sonarsource.com/browse/RSPEC-2327
R# id: _TryStatementsCanBeMerged_

```
try
{
    try
    {
        //Some stuff
    }
    catch (Exception exception)
    {
        log(exception);
        throw;
    }
}
finally
{
    //do something here
}

```
can be converted to
```
try
{
    //Some stuff
}
catch (Exception exception)
{
    log(exception);
    throw;
}
finally
{
    //do something here
}
```

**Comment by ganncamp** [comment]
@tamasvajk this is already written up http://jira.sonarsource.com/browse/RSPEC-2327

**Comment by tvsonar** [comment]
@ganncamp Thanks, and sorry for the noise. (Also, @tamasvajk is my private github user, please use @tvsonar. I should probably merge the two.)

**Comment by dbolkensteyn** [comment]
http://jira.sonarsource.com/browse/RSPEC-2327 is about sibling try statements, whereas the initial example shows a nested one (which can be merged indeed - but which does not have an identical catch clause).

So the 2 rules are different, another RSPEC should be created.

**Comment by ganncamp** [comment]
https://jira.sonarsource.com/browse/RSPEC-1141 probably fits the bill

**Comment by dbolkensteyn** [comment]
@tvsonar Can you collect the cases that are covered by this rule?

Is it just what you provided in the example, or is there more to it?
