### ISSUE TITLE
S2228:  False positive: Reacts to command line programs

### ISSUE THREAD

**Issue by OsirisTerje** [SonarSource-VisualStudio/sonarlint-roslyn-analyzer#203]
Console.Writeline in command line programs also triggers the S2228 warning "Remove this logging statement".  
In a  command line program the Console.Writeline is the way things are written out, and is not used as debug statements.

**Comment by tvsonar** [comment]
@OsirisTerje We see that this rule will always report on console apps. What we initially had in mind was that even in console applications it is not necessarily a good practice to have `Console.WriteLine` all over the code. `Console.WriteLine` can be factorized into a single method, and that method could be called in all the places where you want to write out something. The idea behind this is that if in the future you want to change your app to write to a different output (file, SQL table, HttpResponse), then you only need to change it in one place. 

This way you would have one single issue for this rule, which can be turned off by a single `#pragma warning disable`. Another option is to disable the rule altogether in a ruleset file.

If these don't work for you, then we could modify the rule to exclude files, where there is a `Main()` method. Do you have `Console.WriteLine` in many classes/files?

**Comment by OsirisTerje** [comment]
In smaller console apps it might be in only the main method, but normally they are spread over the code in different classes.  Often the console is the output of choice as it is a console app.  The rule is fine for non-console apps, and might be helpful in console apps too if you want to encapsulate it, as you suggest.  But I guess the issue is that it either should not be default on, or it should detect that it is a console app project and turn off for that, but then - only as the default.

**Comment by dbolkensteyn** [comment]
I tend to agree with you @OsirisTerje - this rule should probably not be enabled by default if it doesn't work well on console apps.
