### ISSUE TITLE
Rule Idea: Flag x.Parse(object.ToString)

### ISSUE THREAD

**Issue by jessehouwing** [SonarSource-VisualStudio/sonarlint-roslyn-analyzer#222]
In code reviews I quite often encounter usage of:

     Convert.ToDecimal(someObjectThatsActuallyADecimal.ToString())
     decimal.Parse(someObjectThatsActuallyADecimal.ToString())

Not only will this cause perfomance issues, it causes loss of precision as well, let alone introduce all kinds of globalization issues.

I've written an FxCop rule in the past that can serve as a starting point:
http://fxcopcontrib.codeplex.com/SourceControl/latest#Main/FxCopContrib/DoNotUseParseAndTostringToConvertTypes.cs

After introducing the rule originally back in VS2010, I've seen a couple of strange tricks to try and outsmart the rules. like:

      decimal.Parse(""+someObjectThatsActuallyADecimal)

And a few others, some of these cases have been worked into this rule.

**Comment by dbolkensteyn** [comment]
@jessehouwing it sounds really strange why anyone would want to do that.
So this rule's purpose is to detect a number being converted into a string, and then back into a number?

**Comment by jessehouwing** [comment]
it would detect an object being converted into a string, then parsed as a number.

if its already a string, casting to string would be much better than calling tostring.
if its already a number, casting would be better.

.tostring is almost always the wrong answer an a possible nullref problem to boot.
