### ISSUE TITLE
Rule idea: Don't create custom delegates

### ISSUE THREAD

**Issue by njannink** [SonarSource-VisualStudio/sonarlint-roslyn-analyzer#223]
C# now has the following delegates in the framework:

EventHandler or EventHandler<>
Action<> variants 
Func<> variants

Having these delegates makes it unneccessary to create your own delegate so I think its a good rule to not create any custom delegates.

**Comment by tvsonar** [comment]
@njannink You are right it is very rarely needed to create your own delegate type. One case which comes to mind is that if you need an `Action` with more than 16 parameters. :-)

When working on early .NET code there won't be any other option than to use `delegate`s. So we'll need to check the framework version.

Finally, I see one benefit of custom delegates. If you have the following:
```
public delegate void MyDelegate(int meaningfulName);
public static event MyDelegate MyEvent;
```
And then you write somewhere `MyEvent += TAB TAB`, then it generates a method for you with a properly named parameter. While if you do the same with an `Action<int>`, the parameter name will be something like `obj` or `argX`. So here you'll need to do a renaming. 

Do you see any other drawbacks of using the delegates from the framework?

**Comment by njannink** [comment]
The only advantage I see for using custom delegates is indeed naming. But I prefer an out-of-the-box type any day than making my own.
