### ISSUE TITLE
Don't implement interfaces explicitly

### ISSUE THREAD

**Issue by tvsonar** [SonarSource-VisualStudio/sonarlint-roslyn-analyzer#371]
In C# if you implement an interface, then the implementation is accessible through the object and the interface reference as well.
```
interface IMyInterface
{
  void DoStuff();
}
class MyClass : IMyInterface
{
  public void DoStuff()
  {
    //important stuff to do
  }
}
....
var instance = new MyClass();
instance.DoStuff();
var interfaceInstance = (IMyInterface)instance;
interfaceInstance.DoStuff();
```
You can also implement an interface explicitly, so it is only available if you access the implementation through the interface:
```
class MyClass : IMyInterface
{
  void IMyInterface.DoStuff()
  {
    //important stuff to do
  }
}
....
var instance = new MyClass();
// instance.DoStuff(); // this would give a compiler error
var interfaceInstance = (IMyInterface)instance;
interfaceInstance.DoStuff();
```
Having both explicit and implicit implementations is also possible. But it can be very confusing, as in this case different methods would be called based on the compile time type information.
Exception: when two interfaces are implemented by a class, and there are colliding methods on the interfaces (method signatures are the same, but the return types are different), then there is no other option then to implement the interfaces explicitly. 
Example from http://stackoverflow.com/questions/143405/c-sharp-interfaces-implicit-implementation-versus-explicit-implementation:
```
public abstract class StringList : IEnumerable<string>
{
    private string[] _list = new string[] {"foo", "bar", "baz"};

    // ...

    #region IEnumerable<string> Members
    public IEnumerator<string> GetEnumerator()
    {
        foreach (string s in _list)
        { yield return s; }
    }
    #endregion

    #region IEnumerable Members
    IEnumerator IEnumerable.GetEnumerator()
    {
        return this.GetEnumerator();
    }
    #endregion
}
```

**Comment by njannink** [comment]
There are cases that its actually needed to explicitly implement interfaces. You want to avoid them as much as possible but it occurs mainly when properties or methods with the same name have different return values or covariant arguments.

Things like:

```
   public interface ISomeExternalInterface
   {
       Guid Id { get; }
       void MyMethod(string arg);
   }

   public interface IMyInterface
   {
       string Id { get; }
       void MyMethod(object arg);
   }

   public class MyClass : IMyInterface, ISomeExternalInterface
   {
       // How to implement both interfaces without Explicit overrides?
   }
```

**Comment by tvsonar** [comment]
@njannink Good that you mentioned it. So we should probably collect a list of exclusions, which need to be considered in the rule:
* when the implemented interfaces have properties/methods with the same signature. If the interfaces are also in the same project, I would not allow this, as this will definitely cause confusion, and we could change the interfaces.
* when the interface is `internal` and the implementing class is `public`. If the interface is explicitly implemented, then the interface members on the class can only be seen from within the assembly, which is a nice way of hiding internal abstractions.

This might also be relevant here: http://blogs.msdn.com/b/ericlippert/archive/2006/04/05/569085.aspx

Do you have any other use-cases when we should "allow" explicit interface implementation?
