### ISSUE TITLE
Custom Exception guidelines

### ISSUE THREAD

**Issue by njannink** [SonarSource-VisualStudio/sonarlint-roslyn-analyzer#501]
There are some guidelines when making your own custom exception:

https://msdn.microsoft.com/en-us/library/vstudio/ms229064(v=vs.100).aspx

- Do not inherit from ```ApplicationException```
- Avoid deep exception hierarchies
- Name should end on Exception
- Exceptions should be serializable ```ISerializable```
- Should not throw exceptions themselfs
- At least have the following constructors:
```
public class MyException : Exception, ISerializable
{
    public NewException()  {  }
    public NewException(string message) 
        : base(message) {  }
    public NewException(string message, Exception inner) 
        : base(message, inner) {  }
 
    // This constructor is needed for serialization.
   protected NewException(SerializationInfo info, StreamingContext context) 
       : base(info, context){  }
}
```

**Comment by tvsonar** [comment]
The naming part is handled by #500
