### ISSUE TITLE
Serialization constructors should be protected or private

### ISSUE THREAD

**Issue by njannink** [SonarSource-VisualStudio/sonarlint-roslyn-analyzer#502]
Constructors needed for serialization (ISerializable) should never be public or internal. They should be protected for non sealed classes and private for internal classes that are never derived and for sealed classes

**Comment by tvsonar** [comment]
https://msdn.microsoft.com/en-us/library/6exf3h2k(v=vs.110).aspx

**Comment by njannink** [comment]
Yes I think we could extract some additional rules from those guidelines. In my project we still use binary serialization through the ISerializable interface so that is what this rule idea was for.
