### ISSUE TITLE
Custom Attributes guidelines

### ISSUE THREAD

**Issue by njannink** [SonarSource-VisualStudio/sonarlint-roslyn-analyzer#503]
As for custom exceptions there are also guidelines when creating your own attributes:

https://msdn.microsoft.com/en-us/library/vstudio/2ab31zeh(v=vs.100).aspx

- Name should end in Attribute
- Should have the ```AttributeUsage``` attribute on top
- Use positional arguments (constructor parameters) for required parameters. Provide a read-only property with the same name as each positional argument, but change the case to differentiate between them. This allows access to the argument at run time.
- Use named arguments for optional parameters and provide a read/write property for each named argument.
- The above 2 rules should not be mixed so its one or the other. Not an required parameter through the constructor that can also be changed through a property

**Comment by tvsonar** [comment]
The naming part is handled by #500
