### ISSUE TITLE
S1514 should report both warning and error for different values

### ISSUE THREAD

**Issue by OsirisTerje** [SonarSource-VisualStudio/sonarlint-roslyn-analyzer#633]
Given that https://github.com/SonarSource/sonarlint-vs/issues/629 is fixed, the rule has only one level, whereas one would like it to have two levels.  
0-10 :  Green  - no warning, no error
10-20:  Yellow - Warning, no error
20--- : Red:  Error 

Also, consider rephrasing the message "greater than 10 authorized", to "greater than warning threshold (10)", and "greater than error threshold (20)".

**Comment by tvsonar** [comment]
@OsirisTerje It's a good idea to assign different severity to the issue based on complexity thresholds, but we don't want to break the build with default settings. Even for rules, internally categorized as blocker rules, such as [this](http://www.sonarlint.org/visualstudio/rules/index.html#version=1.5.0&ruleId=S1697&tags=bug&language=cs), we only report warnings in VS. 

For this specific case, I could imagine two distinct rules, both reporting warnings by default, and then the developer would have the ability to override the default warning severity to error for the higher threshold.

**Comment by OsirisTerje** [comment]
The use of two related rules sounds fine, for those not wanting to break the build on Red,  they could be Hints and Warnings, instead of Warnings and Error.
