### ISSUE TITLE
S2930 False Positive when returning Task of IDisposable

### ISSUE THREAD

**Issue by NArnott** [SonarSource-VisualStudio/sonarlint-roslyn-analyzer#655]
An exception to this rule includes 

    Local IDisposables returned from methods are ignored.

However, that doesn't seem to apply when returning a Task of that IDisposable.

For example, the following code results in a false positive, when the method is clearly not responsible for disposing on the HttpResponseMessage:

    public Task<HttpResponseMessage> ExecuteAsync(CancellationToken cancellationToken)
    {
        HttpResponseMessage response = new HttpResponseMessage(HttpStatusCode.Unauthorized);

        return Task.FromResult(response);
    }

**Comment by tvsonar** [comment]
@NArnott thanks for your feedback. We'll check what we can do. I'm not sure if we want to add an exception to `return AnyExpressionWith(idisposable)` or to just the `Task.FromResult`.

**Comment by dbolkensteyn** [comment]
It seems that this rule has other false positives documented in its unit test, e.g. when a local `IDisposable` is created and then passed as a constructor of another `IDisposable` which gets returned.

Another false positive example is `Task`, which, even if it does implement `IDisposable`, does not *have to* be disposed systematically: http://blogs.msdn.com/b/pfxteam/archive/2012/03/25/10287435.aspx

**Comment by dbolkensteyn** [comment]
`CancellationTokenSource` is another class which does not seem to require to be disposed all the time

**Comment by dbolkensteyn** [comment]
Some classes such as `WaitHandle` provide a `Close()` method synonymous to the `Dispose()` one. Calling `Close` is perfectly fine, but will generate false positives

**Comment by dbolkensteyn** [comment]
Maybe this rule should target only some classes, and not all `IDisposable` ones, to be on the safe side.

I'm thinking about `System.IO` classes for files (with the exception of `MemoryStream`), stream etc or `System.Net` for sockets
