### ISSUE TITLE
Sealed classes with private constructor cannot be instantiated

### ISSUE THREAD

**Issue by tvsonar** [SonarSource-VisualStudio/sonarlint-roslyn-analyzer#663]
R# _ClassCannotBeInstantiated_

```C#
public sealed class MyClass // Noncompliant
{
  private MyClass() { ... }
}
```

`MyClass` can't be instantiated. 

Exception: if you instantiate it inside the class (singleton, or [smart enum](http://blog.falafel.com/introducing-type-safe-enum-pattern/) pattern), or if you use reflection. For the latter one, we can't really have a good check, but it's worth checking if there's any member in the class who has a `MyClass` return type, or parameter type. That's a good indicator that somehow it's possible to create an instance of the class. 

There are probably two compliant solutions
* the constructor should be `public`, or 
* the `sealed` should be removed.

**Comment by ganncamp** [comment]
`sealed` == `final`

**Comment by ganncamp** [comment]
@tvsonar as I start to write this one, I wonder if it's really valid. See:

https://jira.sonarsource.com/browse/RSPEC-2974
https://jira.sonarsource.com/browse/RSPEC-3050
https://jira.sonarsource.com/browse/RSPEC-1118

Further, if we do write this one, I plan to use:
Summary: "sealed" classes should not have only "private" constructors
Message: Un-seal this class, make [at least one of its constructors|its constructor] "public" or add a "public" constructor.
Highlighting: {{sealed class XXX}}

**Comment by tvsonar** [comment]
@ganncamp RSPEC-2974: Classes without "public" constructors should be "final": it's valid to have a `protected` constructor and then only call that from a derived class. So you can't mark the class `sealed` in C# just because it doesn't have a `public` constructor.

RSPEC-3050: Singletons should have "private" constructors: This is true, and in this case there will be a method or property with a return type matching the current class. So as I mentioned in the description above, we are not going to report on these classes.

RSPEC-1118: Utility classes should not have public constructors: there's a subtask for C#. We say that a utility class should be either 
* a `static class`, or
* have a `protected/`private` constructor.
`static class` and `sealed class` can't be mixed, so in the former option we are not covering `sealed` classes. And in the second case, a `private` constructor only makes sense if that's used somewhere, such as in a singleton instantiation, and then again we aren't going to report on it. 

So I think we can add a new RSPEC for this, and it won't trigger issues on the solutions that are suggested by other rules. As for the title: "sealed" classes should not have only "private" constructors, it's okay, as long as we'll add the exception for classes that are instantiated inside the class somewhere. 

For the message I would go with this:
This class is never instantiated, consider un-sealing it, changing the visibility of it's constructor, or making removing the constructor and making the class static.

This last option should only be proposed if all members are `static` in the class.

**Comment by ganncamp** [comment]
Ignore singleton classes, smart enums & utility classes (only static methods) which should be static classes, not sealed

**Comment by ganncamp** [comment]
https://jira.sonarsource.com/browse/RSPEC-3453
