### ISSUE TITLE
"[DefaultValue]" should not be used with "[Optional]" parameters

### ISSUE THREAD

**Issue by tvsonar** [SonarSource-VisualStudio/sonarlint-roslyn-analyzer#665]
R# _DefaultValueAttributeForOptionalParameter_

You can use optional parameters in C# with the following two methods:
```C#
class MyClass
{
    public void DoStuff([Optional]int i, int j = 5)
    {
        Console.WriteLine(i);
    }

    public static void Main()
    {
        new MyClass().DoStuff(); // prints 0
        new MyClass().DoStuff(42); // prints 42
    }
}
```
The second method `int j = 5` defines the default value of the parameter. To define it with the first version, you need to use the `DefaultParameterValueAttribute`. `DefaultParameterValueAttribute` is easy to confuse with `DefaultValueAttribute`. This latter one is on its own has no real usage, it is usually applied to properties to add a default value through Reflection.

**Comment by ganncamp** [comment]
"DefaultValue" has no effect on code. Shows intention.

**Comment by ganncamp** [comment]
https://jira.sonarsource.com/browse/RSPEC-3451
