### ISSUE TITLE
Right operand of shift operators should be an integer

### ISSUE THREAD

**Issue by tvsonar** [SonarSource-VisualStudio/sonarlint-roslyn-analyzer#667]
R# _DynamicShiftRightOpIsNotInt_

You can shift a number with the `<<` and `>>` operators. The right operand of the operation needs to be an `int` or something that has an implicit conversion to `int`, [see here](https://msdn.microsoft.com/en-us/library/a1sway8w.aspx). 

However, with `dynamic` the type checking is turned off, so you can pass anything there. And if that expression can't be converted to `int`, then a runtime exception (`RuntimeBinderException`) will occur.

This compiles, but throws at runtime:
```C#
dynamic d = 5;
var x = d >> 5.4; // Noncompliant
x = d >> null; // Noncompliant
```

**Comment by ganncamp** [comment]
all compiler type checking turned off for `dynamic`

**Comment by ganncamp** [comment]
https://jira.sonarsource.com/browse/RSPEC-3449
