### ISSUE TITLE
Return values should not be ignored when function calls don't have any side effects

### ISSUE THREAD

**Issue by tvsonar** [SonarSource-VisualStudio/sonarlint-roslyn-analyzer#668]
R# _IteratorMethodResultIsIgnored_

LINQ methods don't have side effects.  There's no point in calling them and then not using the result of the iteration.

```C#
coll.Where(i => i > 5).Select(i => i*i); // Noncompliant
```
```C#
var res = coll.Where(i => i > 5).Select(i => i*i); // Compliant
```

**Comment by ganncamp** [comment]
https://jira.sonarsource.com/browse/RSPEC-2201
