### ISSUE TITLE
Loop variable is never changed inside the loop

### ISSUE THREAD

**Issue by tvsonar** [SonarSource-VisualStudio/sonarlint-roslyn-analyzer#669]
R# _LoopVariableIsNeverChangedInsideLoop_

If a `while` loop is checking only a single variable for termination, but that variable is never changed inside the loop, then it's an infinite loop or a useless loop.
```C#
public class MyClass
{
    private MyClass(bool x)
    {
        while (x) // Noncompliant
        {
            //
        }
    }
}
```

**Comment by ganncamp** [comment]
"while (true)" is outside the scope of this rule.

**Comment by ganncamp** [comment]
https://jira.sonarsource.com/browse/RSPEC-2189

**Comment by tvsonar** [comment]
@ganncamp I'm not sure abut this mapping. 
```C#
var b = false;
while (b)
{
  ... do anything here, except assigning to "b"
}
```
In the above case we don't have an infinite loop, we have useless statements that are never executed. Does this fall into RSPEC-2189?

**Comment by ganncamp** [comment]
Example added
