### ISSUE TITLE
Exceptions should be rethrown

### ISSUE THREAD

**Issue by tvsonar** [SonarSource-VisualStudio/sonarlint-roslyn-analyzer#672]
R# _PossibleIntendedRethrow_

When catching an exception, and then rethrowing it, you should do it by calling `throw;` and not `throw exc;`, because in the latter case you lose the stack trace information, and debugging becomes a lot harder.

```C#
try
{}
catch(Exception exc)
{
  Console.WriteLine(exc);
  throw exc; //Noncompliant
  throw; //Compliant
  throw new Exception("My custom message", exc);  // Compliant
}
```

**Comment by ganncamp** [comment]
https://jira.sonarsource.com/browse/RSPEC-3445

**Comment by tvsonar** [comment]
Note: we need to check if CA2200 is already implemented by Roslyn or not, and why it doesn't show up in the IDE.
