### ISSUE TITLE
Type examining methods should be avoided on "System.Type" instances

### ISSUE THREAD

**Issue by tvsonar** [SonarSource-VisualStudio/sonarlint-roslyn-analyzer#675]
R# _PossibleMistakenCallToGetType.*_

`type.GetType()` doesn't make sense

```C#
var type = typeof(int);
var ttype = type.GetType(); //Noncompliant, will always return typeof(System.Type)
```

`type.IsInstanceOfType(expression.GetType())` is probably not what was meant, because it's only true, if `type == typeof(System.Type)`:

```C#
var s = typeof (string).IsInstanceOfType("ssss".GetType()); //Noncompliant, false
//this was meant probably: 
s = typeof (string).IsInstanceOfType("ssss"); // true

var x = typeof (Type).IsInstanceOfType("ssss".GetType()); // true
```

**Comment by ganncamp** [comment]
make sure to cover https://github.com/SonarSource/sonarlint-vs/issues/674

**Comment by ganncamp** [comment]
https://jira.sonarsource.com/browse/RSPEC-3443
