### ISSUE TITLE
"abstract" classes should not have "public" constructors

### ISSUE THREAD

**Issue by tvsonar** [SonarSource-VisualStudio/sonarlint-roslyn-analyzer#677]
R# _PublicConstructorInAbstractClass_

Could be part of https://jira.sonarsource.com/browse/RSPEC-2333

```C#
abstract class Base
{
    public Base() // Noncompliant, should be private or protected, the class can't be instantiated anyways.
    {

    }
}

```

**Comment by ganncamp** [comment]
can have basic initialization logic in private/protected constructor which extending classes would call.
in C# base class constructor called automatically

**Comment by ganncamp** [comment]
https://jira.sonarsource.com/browse/RSPEC-3442
