### ISSUE TITLE
"unsafe" context is redundant

### ISSUE THREAD

**Issue by tvsonar** [SonarSource-VisualStudio/sonarlint-roslyn-analyzer#681]
R# _RedundantUnsafeContext_

either there are no unsafe constructs inside, or we are already inside an unsafe context

```C#
unsafe
{
   unsafe // Noncompliant, we are already in an unsafe context
   {
     int i = 42;
     var address = &i;
     *address = 43;
     Console.WriteLine(i);
  }
}
```
Other variant:
```C#
public unsafe void MyMethod()
{
    unsafe // Noncompliant, we are already in an unsafe context
    {
        int i = 42;
        var address = &i;
        *address = 43;
        Console.WriteLine(i);
    }
}
```

And a 3rd case, when there's no unsafe construct inside the block:
```C#
public unsafe void MyMethod() // Noncompliant, the method doesn't use unsafe constructs
{
    int i = 42;
    Console.WriteLine(i);
}
```

Issue location: the `unsafe` keyword can be faded as unused code.

**Comment by ganncamp** [comment]
https://jira.sonarsource.com/browse/RSPEC-2333 ?

**Comment by ganncamp** [comment]
I've mapped this to https://jira.sonarsource.com/browse/RSPEC-2333, which is already implemented in C#, so you'll need to extend the implementation scope
