### ISSUE TITLE
Limit nesting depth of control flow statements in functions

### ISSUE THREAD

**Issue by p3pijn** [SonarSource-VisualStudio/sonarlint-roslyn-analyzer#684]
I would like to suggest a new rule which limits the nesting depth of control flow statements to a certain value.

Many software quality standards describe a maximum nesting depth of control flow statements per function. An example of this the IfSQ level 2 standard for maintainable source code (http://www.ifsq.org/level-2.html), which prescribes a maximum nesting depth of 4 (see: http://www.ifsq.org/indicator-SP-2.html).
Another well known set of coding guidelines that limit the nesting depth to 1 control structure are the Object Calisthenics by Jeff Bay (http://www.cs.helsinki.fi/u/luontola/tdd-2009/ext/ObjectCalisthenics.pdf).

Although this rule is slightly related to limiting the cyclomatic complexity of functions to a certain value, being able to limit the nesting depth at the function level still provides a valuable addition. For example, when the nesting depth of control flow statements of a function exceeds 4 the function is considered to be hard to understand, while the cyclomatic complexity of the function might still fall within the acceptable range of 5 to 10.

I would suggest a default value of 4 for the maximum nesting depth at the function level (in accordance to the IfSQ level 2 standard). Whereas users should be able to change the value according to their needs.

**Comment by tvsonar** [comment]
Thanks @p3pijn. I just did a searhc in our rule repository, and found the following rule, which covers what you propose: https://jira.sonarsource.com/browse/RSPEC-134. So we can implement it relatively quickly.
