### ISSUE TITLE
Methods should not have too many lines

### ISSUE THREAD

**Issue by p3pijn** [SonarSource-VisualStudio/sonarlint-roslyn-analyzer#685]
I would like to issue a request for a C# implementation of the rule "Methods should not have too many lines" (See: https://jira.sonarsource.com/browse/RSPEC-138). Even though this rule seems rather trivial, I think it is one of the most powerful rules to help teams keeping code concise to promote understandability, testability and reuse. Therefore this rule is a valuable addition to the existing SonarLint VS rules.

The default value for this rule could be argued about. IfSQ level 2 suggests a threshold of 200 lines for a procedure (http://www.ifsq.org/indicator-SP-1.html). TUViT/SIG suggest a maximum of 15 lines of code (excluding comments and white space) (see https://www.youtube.com/watch?v=aLwIyFMF-iw&t=19m18s). Object Calisthenics even suggests a maximum of 5 lines of code (http://www.cs.helsinki.fi/u/luontola/tdd-2009/ext/ObjectCalisthenics.pdf).

Valuable configuration settings for this rule would be:
- Being able to configure the threshold value
- Exclude comments / white-space

Similar to the rule "Files should not have too many lines".

**Comment by dbolkensteyn** [comment]
IMO any method with >= 1 lines of code is already problematic since it can be source of bugs ;) (sorry... it's Friday...)

**Comment by tvsonar** [comment]
@p3pijn Until there's no easy way to set rule parameters in Visual Studio, we are not likely to implement this rule. As you mentioned it's similar to the file length rule, about which we get complaints, so in the end we disabled it.

**Comment by kevinpdpath** [comment]
Rule parameters can be set via SonarLint.xml, as of https://github.com/SonarSource/sonarlint-vs/pull/631

You need to include a file called SonarLint.xml as an AdditionalFile in your project. See https://github.com/dotnet/roslyn/blob/master/docs/analyzers/Using%20Additional%20Files.md

**Comment by dbolkensteyn** [comment]
@kevinpdpath The plan with this XML file is to synchronize it with your SonarQube server instance, to get consistent issues in the IDE and in SonarQube. This will be part of SonarLint VS 2.x, that will provide this "connected mode".

At the moment we're not thinking to document this feature, we don't expect users to manually edit this XML file. Currently, this XML file is only expected to be used by the SonarQube Scanner for MSBuild.
