### ISSUE TITLE
Pure method's return value is not used

### ISSUE THREAD

**Issue by tvsonar** [SonarSource-VisualStudio/sonarlint-roslyn-analyzer#717]
R# _ReturnValueOfPureMethodIsNotUsed_

Methods can be marked with `[Pure]` attribute to show that their return value only depends on the inputs, and that no visible change is made to the object that it's called on. Not using the return value of such method makes the method call redundant.

**Comment by ganncamp** [comment]
https://jira.sonarsource.com/browse/RSPEC-1154
