### ISSUE TITLE
Suspicious type conversion or check

### ISSUE THREAD

**Issue by tvsonar** [SonarSource-VisualStudio/sonarlint-roslyn-analyzer#719]
R# _SuspiciousTypeConversion.Global_

R# description of the issue:
One type is converted to another but there is no type in the solution which is interited from both. Also applies to 'is' operator and '==' and '!=' comparisons.

```C#
public interface MyInterface
{
}

public class MyClass
{
}

public static class Program
{
    public static void Main()
    {
        var myclass = new MyClass();
        var x = (MyInterface) myclass; // Noncompliant
    }
}

```

**Comment by ganncamp** [comment]
invalid cast to an interface (compiler catches invalid cast to class)

**Comment by ganncamp** [comment]
https://jira.sonarsource.com/browse/RSPEC-1944
