### ISSUE TITLE
Autoproperty accessor is never used

### ISSUE THREAD

**Issue by tvsonar** [SonarSource-VisualStudio/sonarlint-roslyn-analyzer#721]
R# _UnusedAutoPropertyAccessor.Local_

`public int MyProp {get;set;}`, if any of the accessors is never used, it can simply be removed.

**Comment by ganncamp** [comment]
https://jira.sonarsource.com/browse/RSPEC-1144 (private)
https://jira.sonarsource.com/browse/RSPEC-1815 (protected)

**Comment by njannink** [comment]
When using a framework like Mef you might get a lot of false positives on this rule.

    [Import] IMyService { get; set; }

If you implement this rule you should also provide a way to indicate items are used implicitly. R# has custom annotations for this.
