### ISSUE TITLE
Not report issues in the body of the "initializeComponent()" function generated by old version of Windows Form Designer

### ISSUE THREAD

**Issue by fmallet** [SonarSource-VisualStudio/sonarlint-roslyn-analyzer#730]
Old version of the Windows Form Designer was mixing generated and hand-written source code in the same source file. When function "initializeComponent()" is called from a constructor of such Form, the body of the "initializeComponent()" function should be considered as "generated" and so no issue should be reported against it.

**Comment by njannink** [comment]
Instead of ignoring InitializeComponent() methods code in .designer.cs files and in the following regions should be ignored:

    #region Windows Form Designer generated code
    #region Component Designer generated code
    #region Designer generated code
    #region Web Form Designer generated code

Since that is what the old forms code generation makes.

**Comment by dbolkensteyn** [comment]
do you mean that you know of other use cases @njannink besides `InitializeComponent()` ?
