### ISSUE TITLE
Make use of (custom) annotations to guide analysis

### ISSUE THREAD

**Issue by njannink** [SonarSource-VisualStudio/sonarlint-roslyn-analyzer#731]
Since you guys are becomming a stronger competitor to Resharper if would be nice that your analysis engine can also make use of custom annotations to be able to have less false positives and to be able to find programming errors.

First simple annotations that come into mind are:
[NotNull] [Null] to indicate if arguments / return values can be null
[Localizable] to indicate if something need or doesn't need to be localized
[UsedImplicitly] to indicate that a member is used implicitly

etc.

**Comment by dbolkensteyn** [comment]
That's a good idea indeed @njannink 

Do you have particular rules in mind that would benefit from this? It would make this issue more "actionable", I have the feeling that going through every existing rule to check if these attributes apply is not going to happen any time soon. So it's best to write down the rule IDs as you encounter these false positives and comment here.

Thanks again
